name: Test and Deploy to Render

on:
  workflow_dispatch:
  push:
    branches:
      - develop
jobs:

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 16

      - name: Install dependencies
        run: npm install
    
      - name: Run test
        uses: cypress-io/github-action@v6
        with:
          start: node index.js
          browser: chrome

  backend-reservations-test:
   runs-on: ubuntu-latest
  
   steps:
     - name: Checkout code
       uses: actions/checkout@v4.1.1

     - name: Set up Node.js
       uses: actions/setup-node@v4.0.2
       with:
          node-version: 20.10.0

     - name: Install dependencies
       run: npm install
     - name: Run test
       run: npm test scripts/reservations.test.js -- --reporters=default --reporters=jest-junit
     - name: Test Summary
       uses: test-summary/action@v2
       with:
         paths: "**/junit.xml"
       if: always()

  backend-notifications-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.10.0

    - name: Install dependencies
      run: npm install
    - name: Run test
      run: npm test scripts/notifications.test.js -- --reporters=default --reporters=jest-junit
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "**/junit.xml"
      if: always()
    
  backend-accounts-test:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
    
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.10.0
    
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test scripts/accounts.test.js -- --reporters=default --reporters=jest-junit
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "**/junit.xml"
        if: always()


  deploy-to-render:
    runs-on: ubuntu-latest
    needs: [backend-reservations-test,backend-notifications-test,backend-accounts-test,frontend-test]

    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.10.0

    - name: Install dependencies
      run: npm install

    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}
        

